# fly.toml app configuration file generated for portfolio-backend-go on 2024-12-23T14:38:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'portfolio-backend-go'
primary_region = 'scl'

[build]
  [build.args]
    GO_VERSION = '1.23.2'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
